// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: attendance_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendanceMember = `-- name: CreateAttendanceMember :one
INSERT INTO attendance_members
(
  stream_id,
  username,
  is_shouted,
  present_at
)
VALUES
($1, $2, $3, $4)
RETURNING id, stream_id, username, is_shouted, present_at, created_at
`

type CreateAttendanceMemberParams struct {
	StreamID  int64              `json:"stream_id"`
	Username  string             `json:"username"`
	IsShouted bool               `json:"is_shouted"`
	PresentAt pgtype.Timestamptz `json:"present_at"`
}

func (q *Queries) CreateAttendanceMember(ctx context.Context, arg CreateAttendanceMemberParams) (AttendanceMember, error) {
	row := q.db.QueryRow(ctx, createAttendanceMember,
		arg.StreamID,
		arg.Username,
		arg.IsShouted,
		arg.PresentAt,
	)
	var i AttendanceMember
	err := row.Scan(
		&i.ID,
		&i.StreamID,
		&i.Username,
		&i.IsShouted,
		&i.PresentAt,
		&i.CreatedAt,
	)
	return i, err
}
