// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: streams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStream = `-- name: CreateStream :one
INSERT INTO streams
(
  user_id,
  title,
  game_name,
  started_at,
  created_by
)
VALUES
($1, $2, $3, $4, $5)
RETURNING id, user_id, title, game_name, started_at, created_at, created_by
`

type CreateStreamParams struct {
	UserID    int64              `json:"user_id"`
	Title     string             `json:"title"`
	GameName  string             `json:"game_name"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	CreatedBy int64              `json:"created_by"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error) {
	row := q.db.QueryRow(ctx, createStream,
		arg.UserID,
		arg.Title,
		arg.GameName,
		arg.StartedAt,
		arg.CreatedBy,
	)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.GameName,
		&i.StartedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteStream = `-- name: DeleteStream :exec
DELETE FROM streams
WHERE id = $1
`

func (q *Queries) DeleteStream(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStream, id)
	return err
}

const getStream = `-- name: GetStream :one
SELECT id, user_id, title, game_name, started_at, created_at, created_by FROM streams
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStream(ctx context.Context, id int64) (Stream, error) {
	row := q.db.QueryRow(ctx, getStream, id)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.GameName,
		&i.StartedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listStreams = `-- name: ListStreams :many
SELECT id, user_id, title, game_name, started_at, created_at, created_by FROM streams
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListStreamsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStreams(ctx context.Context, arg ListStreamsParams) ([]Stream, error) {
	rows, err := q.db.Query(ctx, listStreams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stream
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.GameName,
			&i.StartedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
