// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions
(
  id,
  user_id,
  refresh_token,
  user_agent,
  client_ip,
  is_blocked,
  expires_at,
  encrypted_twitch_token
)
VALUES
($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, encrypted_twitch_token
`

type CreateSessionParams struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	RefreshToken         string             `json:"refresh_token"`
	UserAgent            string             `json:"user_agent"`
	ClientIp             string             `json:"client_ip"`
	IsBlocked            bool               `json:"is_blocked"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	EncryptedTwitchToken string             `json:"encrypted_twitch_token"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
		arg.EncryptedTwitchToken,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EncryptedTwitchToken,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, encrypted_twitch_token FROM sessions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EncryptedTwitchToken,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, encrypted_twitch_token FROM sessions
WHERE refresh_token = $1 AND is_blocked = false
LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EncryptedTwitchToken,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT s.id, s.user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, s.created_at, encrypted_twitch_token, u.id, u.user_id, user_login, user_name, profile_image_url, u.created_at, updated_at FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE u.user_id = $1 AND is_blocked = false
ORDER BY s.created_at DESC
LIMIT 1
`

type GetSessionByUserIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	RefreshToken         string             `json:"refresh_token"`
	UserAgent            string             `json:"user_agent"`
	ClientIp             string             `json:"client_ip"`
	IsBlocked            bool               `json:"is_blocked"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	EncryptedTwitchToken string             `json:"encrypted_twitch_token"`
	ID_2                 int64              `json:"id_2"`
	UserID_2             string             `json:"user_id_2"`
	UserLogin            string             `json:"user_login"`
	UserName             string             `json:"user_name"`
	ProfileImageUrl      string             `json:"profile_image_url"`
	CreatedAt_2          pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSessionByUserID(ctx context.Context, userID string) (GetSessionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByUserID, userID)
	var i GetSessionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EncryptedTwitchToken,
		&i.ID_2,
		&i.UserID_2,
		&i.UserLogin,
		&i.UserName,
		&i.ProfileImageUrl,
		&i.CreatedAt_2,
		&i.UpdatedAt,
	)
	return i, err
}

const listSession = `-- name: ListSession :many
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, encrypted_twitch_token FROM sessions
ORDER BY created_at ASC
`

func (q *Queries) ListSession(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSession)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.EncryptedTwitchToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET
  encrypted_twitch_token = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, encrypted_twitch_token
`

type UpdateSessionParams struct {
	ID                   pgtype.UUID `json:"id"`
	EncryptedTwitchToken string      `json:"encrypted_twitch_token"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.ID, arg.EncryptedTwitchToken)
	return err
}
