// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserConfig = `-- name: CreateUserConfig :one
INSERT INTO user_configs
(
  user_id,
  config_type,
  "value"
)
VALUES
($1, $2, $3)
RETURNING id, user_id, config_type, value, created_at, updated_at
`

type CreateUserConfigParams struct {
	UserID     int64       `json:"user_id"`
	ConfigType ConfigTypes `json:"config_type"`
	Value      string      `json:"value"`
}

func (q *Queries) CreateUserConfig(ctx context.Context, arg CreateUserConfigParams) (UserConfig, error) {
	row := q.db.QueryRow(ctx, createUserConfig, arg.UserID, arg.ConfigType, arg.Value)
	var i UserConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConfigType,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserConfig = `-- name: DeleteUserConfig :exec
DELETE FROM user_configs
WHERE id = $1
`

func (q *Queries) DeleteUserConfig(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserConfig, id)
	return err
}

const getUserConfig = `-- name: GetUserConfig :one
SELECT uc.id, uc.user_id, config_type, value, uc.created_at, uc.updated_at, u.id, u.user_id, user_login, user_name, profile_image_url, u.created_at, u.updated_at FROM user_configs uc
JOIN users u ON u.id = uc.user_id
WHERE uc.user_id = $1 AND uc.config_type = $2
LIMIT 1
`

type GetUserConfigParams struct {
	UserID     int64       `json:"user_id"`
	ConfigType ConfigTypes `json:"config_type"`
}

type GetUserConfigRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	ConfigType      ConfigTypes        `json:"config_type"`
	Value           string             `json:"value"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID_2            int64              `json:"id_2"`
	UserID_2        string             `json:"user_id_2"`
	UserLogin       string             `json:"user_login"`
	UserName        string             `json:"user_name"`
	ProfileImageUrl string             `json:"profile_image_url"`
	CreatedAt_2     pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2     pgtype.Timestamptz `json:"updated_at_2"`
}

func (q *Queries) GetUserConfig(ctx context.Context, arg GetUserConfigParams) (GetUserConfigRow, error) {
	row := q.db.QueryRow(ctx, getUserConfig, arg.UserID, arg.ConfigType)
	var i GetUserConfigRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConfigType,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID_2,
		&i.UserLogin,
		&i.UserName,
		&i.ProfileImageUrl,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const updateUserConfig = `-- name: UpdateUserConfig :one
UPDATE user_configs
SET "value" = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, config_type, value, created_at, updated_at
`

type UpdateUserConfigParams struct {
	ID    int64  `json:"id"`
	Value string `json:"value"`
}

func (q *Queries) UpdateUserConfig(ctx context.Context, arg UpdateUserConfigParams) (UserConfig, error) {
	row := q.db.QueryRow(ctx, updateUserConfig, arg.ID, arg.Value)
	var i UserConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConfigType,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
