name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3-alpine3.19
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sopostgres
          POSTGRES_DB: go-so
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6666:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22.0
      id: go

    - name: Install golang-migrate
      run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz

    - name: Install sqlc
      run: make installsqlc

    - name: Run migrations
      run: make migrateup

    - name: Run sqlc
      run: make sqlc

    - name: Test
      run: make test
